<?php
/**
 * @file
 * Full Canlendar Views module help and theme functions.
 */

// Store the preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('fullcalendar_view', 'inc', 'fullcalendar_view.theme');

/**
 * Implements hook_theme().
 */
function fullcalendar_view_theme($existing, $type, $theme, $path) {
  return array(
    'fullcalendar' => array(
      'file' => 'fullcalendar_view.theme.inc',
    ),
  );
}