<?php
/**
 * Implements hook_library_info_alter().
 */
function calendar_recurring_event_library_info_alter(array &$libraries, $module) {
  if ('calendar_recurring_event' == $module) {
    // Use CDN instead of all local missing libraries.
    // RRule js.
    $cdn_library = _calendar_recurring_event_use_cdn($libraries, 'libraries.rrule', 'js');
    if ($cdn_library) {
      $libraries['libraries.rrule']['js'] = $cdn_library;
    }
  }
}

/**
 * Replace local library with CDN.
 *
 * @param array $libraries
 *   The libraries array.
 * @param string $library_name
 *   The library name.
 * @param string $type
 *   The library type.
 * @param bool $replace_local
 *   Force to replace local libraries with CDN.
 *
 * @return array
 *   The new library array (CDN)
 */
function _calendar_recurring_event_use_cdn(array $libraries, $library_name, $type, $replace_local = FALSE) {
  if (isset($libraries[$library_name])) {
    if (isset($libraries[$library_name][$type]) && isset($libraries[$library_name]['cdn'])) {
      $library_array = [];
      $updated = FALSE;
      // CSS library has a sub-array called component.
      if ($type === 'css') {
        if (isset($libraries[$library_name][$type]['component'])) {
          $local_library = $libraries[$library_name][$type]['component'];
        }
        else {
          return FALSE;
        }
      }
      else {
        // Local js library.
        $local_library = $libraries[$library_name][$type];
      }
      foreach ($local_library as $key => $value) {
        if (!file_exists(DRUPAL_ROOT . $key) || $replace_local) {
          // The js file doesn't exist.
          // Replace it with remote cdn.
          $library_array[$libraries[$library_name]['cdn']] = $value;
          $updated = TRUE;
        }
        else {
          $library_array[$key] = $value;
        }
      }
    }
  }
  
  return empty($updated) ? FALSE : $library_array;
}